name: Multi Command Workflow
on: workflow_dispatch
jobs:
  multi-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: running-multiple-commands
        run: |
          echo "srinu"
          echo "chintha"
          
